sudo: required
dist: trusty
addons:
  artifacts:
    paths:
    - results
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
  - bower_components
  - $HOME/.npm
  - $HOME/.cache
before_script:
- npm install
before_deploy:
- npm run build
env:
  global:
  - NODE_ENV=testing
  - ARTIFACTS_BUCKET=javascript-automation
  - secure: WVVPWDG2/D6RSgZd7Q4exQdl6y9Ck342KZXuCx4yCCmGYq1q6Sx5tTfhAQso9aaeJf+WOZpIExldmyqWtL9/p9PUXntz07mFdDyFpThwg8lhcKtqJKAmw85Gs7h7lUX2zkC1pY/2gLjDIqE+qPKwbWcUDUWX8cN/5Ur18S3GhTColqIUM3NW5E7mHlP3BBMja3J/xxwjTn+Ghw3Pc/yHvQyP2NgVEo99tLjOP7CqwontfaNSfp5AeTqPuc7waHr+GOAYTJfX0SWQL8SBZeJ2f4XLXwxbKqxIBmNImh28pOnUgNgpr+DDSyg/+MeTbpqittjCmZbADuO9rMq+MVtCy/5jZRNUfWxImGfiERuY7+EBYWJvFRb7E38gpZal6pvQasqyPQQNlmYw+VlgMrdB1IOgWSon8dOFi1sonBKWtRUzI3HqoPFDbBkmoSPRO04rUOVGFBk/aRa/cSzOAfmQmjYIt26+7ZZbm4JuYpdagjuu10QOkDRbfJFl6pk04RTuCeZJHWbW++AEPpxwlyQ1XI67CGhCIUhacakYgZ+iQQW5wEZgwaBUeYR2iCKhb99bDghcuzuApAgZnrp3o8HtKIeHS96fpCVMxM9mmVoCW8qvCKI5j4lCQBkMhYx3QGP4JKfej4kQTY0OksoTwoXKVNKU2b85hC50VU+IAKIFe2Y=
  - secure: NURs+IfJjYflshUb+Q6Ybai8jkKJVZ0hIqLl7sLP2JEAQyrKUwVmaXBEKGK7YlZD0omb4jVex9G0jmxDp3grvGeZjuudSiSCzqobPQYD8/hG8wj+dhkoiaFIK2DlTFvxrvg7wNWKEFFak/EXOpHW0ZAs/ggQRj1y+T3yrTIf4LwyxrYeRvBJkLVhEcqzqdf8IRpnwn3XQWtXBQgdkxgwmba909lfEazynZp+SM2Z7W2mnyFwWyB4lYx/6m3l+y1rqwd6GSThs1pIoTwPLMtzo+bWBhn1NvhFGbk4WFxsNl4lSliN5lJnd12yDRs3Fh8V+RuEASuG3oMrnoF1B6tn2m+rZHjKz0HLnYZLGO4nvoSi+JNs2El6scmDZB/2PGnkXFsKsl4TBqp8VkOxZ8Huj0KpxSUdjyvPmuP55//VcaHPGageMcHxpcSlxHBgntx7KteP/MC6OUEMaoRrK2HQKDBZMu8EGSOqVhL2u2jJ54iaGtn+gaWHQSavY2cI+GBCVeQWzLwKQztiaOVl0Z5OWyV5XwA2HQoPU5v2mr8NdQAyAQx14jAFQzVRlSNCWAttm2NC98RzQHnmlExkihy9XnofsETOdYLXXL2fefWFxOozpfuT9BhM2abwGom83tbPEl/G7dtN1eaFZMgnrfWArLtSTP5PfHtPQCQIzYuVsWM=
script:
- npm run test
notifications:
  webhooks: http://ec2-54-234-52-201.compute-1.amazonaws.com/courses/ci/build
